server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///traveldb?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.tbs.pojo
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
