spring:
  datasource:
    url: jdbc:mysql://192.168.186.131:3306/traveldb?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 184686
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      cache: false
      #避免改了模板还要重启服务器

mybatis:
  type-aliases-package: com.yh.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

server:
  port: 80

logging:
  config: classpath:logback.xml
