spring:
  datasource:
    url: jdbc:mysql:///traveldb?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
      cache: false
      #避免改了模板还要重启服务器

mybatis:
  type-aliases-package: com.yh.pojo
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql

server:
  port: 80
